// Generated by CoffeeScript 1.9.3
(function() {
  var force, getData, getLinks, graph, h, height, link, linkScale, links, m, node, nodeByName, nodes, nodesByName, rScale, svg, viz, w, width;

  graph = window.fixtures[0];

  getData = function(graph) {
    var nodes;
    return nodes = {
      nodes: _.values(graph.nodes),
      links: _.values(graph.edges)
    };
  };

  getLinks = function(graph) {
    var edges;
    edges = _.values(graph.edges);
    return edges.map(function(e) {
      return {
        "source": e.nodes[0],
        "target": e.nodes[1]
      };
    });
  };

  viz = document.getElementById('viz');

  width = 900;

  height = 900 / viz.offsetWidth * viz.offsetHeight;

  m = {
    top: 10,
    bottom: 10,
    right: 10,
    left: 10
  };

  w = width - m.left - m.right;

  h = height - m.top - m.bottom;

  force = d3.layout.force().charge(-20).gravity(0.3).size([width, height]).linkStrength(0.9).friction(0.5).theta(0.8).alpha(0.1);

  rScale = d3.scale.linear().domain([0, 1]).range([0, 3]);

  linkScale = d3.scale.linear().domain([0, 1]).range([10, 0]);

  svg = d3.select("#viz").append("svg").attr({
    "viewBox": "0 0 " + width + " " + height,
    "preserveAspectRatio": "xMidYMin slice",
    "width": "100%"
  }).style({
    "padding-bottom": (100 * height / width) + "%",
    "height": "1px",
    "overflow": "visible"
  }).append("g").attr("transform", "translate(" + m.left + "," + m.top + ")");

  links = getLinks(window.fixtures[0]);

  nodesByName = {};

  nodeByName = function(name) {
    return nodesByName[name] || (nodesByName[name] = {
      name: name
    });
  };

  links.forEach(function(link) {
    link.source = nodeByName(link.source);
    return link.target = nodeByName(link.target);
  });

  nodes = d3.values(nodesByName);

  console.log(nodes.length);

  console.log(links.length);

  force.nodes(nodes).links(links).linkDistance(function(d) {
    m = graph.edges[d.source.name + '-' + d.target.name].weight.metric;
    return linkScale(m);
  }).start();

  link = svg.selectAll(".link").data(links).enter().append("line").attr("class", "link");

  node = svg.selectAll(".node").data(nodes).enter().append("circle").attr("class", "node").attr("r", function(d) {
    var error;
    try {
      console.log(graph.nodes[d.name].type);
      if (graph.nodes[d.name].type === "topic") {
        return 7;
      } else {
        return rScale(graph.nodes[d.name].weight.metric);
      }
    } catch (_error) {
      error = _error;
      return 2;
    }
  }).call(force.drag);

  node.append("title").text(function(d) {
    return d.name;
  });

  force.on("tick", function() {
    link.attr("x1", function(d) {
      return d.source.x;
    }).attr("y1", function(d) {
      return d.source.y;
    }).attr("x2", function(d) {
      return d.target.x;
    }).attr("y2", function(d) {
      return d.target.y;
    });
    return node.attr("cx", function(d) {
      return d.x;
    }).attr("cy", function(d) {
      return d.y;
    });
  });

}).call(this);
